dist: trusty
sudo: false

language: node_js
node_js:
  - '8.15'

notifications:
  on_success: never
  on_failure: always

cache:
  directories:
    - node_modules

script:
  - echo $TRAVIS_TAG

before_deploy:
  - npm run build
  - ls .
  - zip -r build-$TRAVIS_TAG.zip build

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: build-$TRAVIS_TAG.zip
  skip_cleanup: true
  draft: true
  on:
    tags: true
    all_branches: true
