language: node_js
node_js: "10"
cache: npm

branches:
  only:
    - develop
    - master
    - /^\d{4}-\d{2}-\d{2}-\d+$/

env:
  global:
    - PATH=$HOME/.local/bin:$PATH # for `aws`

install:
  - npm ci
  - pip install --user awscli

script:
  - npm run build
  - zip -r build-$TRAVIS_TAG.zip build
  - echo "Bundle SHA-256 checksum $(sha256sum build-$TRAVIS_TAG.zip)"

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_BUCKET
    skip_cleanup: true
    region: us-east-2
    local_dir: build
    on:
      branch: develop
    cache_control: "max-age=$CACHE_MAX_AGE"

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_BUCKET
    skip_cleanup: true
    region: us-east-2
    local_dir: build
    on:
      branch: master
    cache_control: "max-age=$CACHE_MAX_AGE"

  - provider: releases
    api_key: $GH_TOKEN
    file: build-$TRAVIS_TAG.zip
    skip_cleanup: true
    draft: true
    name: $TRAVIS_TAG
    on:
      tag: true
      condition: $TRAVIS_TAG =~ ^\d{4}-\d{2}-\d{2}-\d+$

after_deploy:
  - aws configure set preview.cloudfront true
  # - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
