language: node_js
node_js: "10"
dist: bionic
cache: npm

branches:
  only:
    - develop
    - master
    - deploy-test

env:
  global:
    - PATH=$HOME/.local/bin:$PATH # for `aws`

install:
  - npm ci

script:
  - npm run build

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_BUCKET
    skip_cleanup: true
    region: us-east-2
    local_dir: build
    on:
      branch: develop
    cache_control: "max-age=$CACHE_MAX_AGE"

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_BUCKET
    skip_cleanup: true
    region: us-east-2
    local_dir: build
    on:
      branch: master
    cache_control: "max-age=$CACHE_MAX_AGE"

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "metronome.io"
    acl: public_read
    skip_cleanup: true
    region: us-east-2
    local_dir: build
    on:
      branch: deploy-test
      #    cache_control: "max-age=$CACHE_MAX_AGE"

after_deploy:
  - pip install --user awscli
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
