language: node_js
node_js: '10'
cache: npm

branches:
  only:
    - develop
    - master

env:
  global:
    - PATH=$HOME/.local/bin:$PATH # for `aws`

script:
  - npm run build

before_deploy:
  - pip install --user awscli
  - aws s3 rm s3://$S3_BUCKET --recursive
  - ls .
  - zip -r build-$TRAVIS_TAG.zip build
  - echo "Bundle SHA-256 checksum $(sha256sum build-$TRAVIS_TAG.zip)"

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_BUCKET
    skip_cleanup: true
    region: us-east-2
    local_dir: build
    on:
      branch: develop
    cache_control: 'max-age=$CACHE_MAX_AGE'

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_BUCKET
    skip_cleanup: true
    region: us-east-2
    local_dir: build
    on:
      branch: master
    cache_control: 'max-age=$CACHE_MAX_AGE'

  - provider: releases
    api_key: $GH_TOKEN
    file: build-$TRAVIS_TAG.zip
    skip_cleanup: true
    draft: true
    name: $TRAVIS_TAG
    on:
      branch: master

after_deploy:
  - aws configure set preview.cloudfront true
  # - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
